### ISSUE TITLE
Remove some of the more annoying sounds

### ISSUE THREAD

**Issue by BannanaRepublic** [Sunconure11/dungeon-mobs#19]
Like the Troll for example. At least maybe lower volume? 

Thanks for remaking this BTW, love this mod. You are doing such a great job with this. In the future maybe you could see about bringing back "Better Dungeons" too.

**Comment by BannanaRepublic** [comment]
Plus till getting the 

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_70068_e(Entity.java:1459)
	at com.gw.dm.ai.EntityAIFollowTwin.func_75253_b(EntityAIFollowTwin.java:37)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:108)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at com.gw.dm.EntityDungeonMob.func_70636_d(EntityDungeonMob.java:47)
	at com.gw.dm.entity.EntityLizalfos.func_70636_d(EntityLizalfos.java:344)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by BlackJar72** [comment]
What version?  A new one?  Also, single player of server; crashing servers use to be a common problem, not sure about single player.

I thought I'd fixed that, but now I'm at a loss -- this is why I always kept lizalfos turned on in old versions.

**Comment by BlackJar72** [comment]
I have made some new mini-bosses quiter (in the code the determines how far away they can be heard).  I'm not getting rid of any sounds or making any notably quiet though -- the sounds can be unnerving, but also helps players survive by warning them when of nearby danger (except for a couple exceptions, because some surprises are OK).

I'm considering this to be about lizalfos now, though I'm not sure I can fix it.

**Comment by BlackJar72** [comment]
Also, I'm not sure about Sunconure11, but as cool as better dungeons was right now I've already bitten off more than I can chew (or had planned to).

**Comment by BannanaRepublic** [comment]
Never thought about the sounds being for a warning to players. Good point. I think the troll is really the only one that is super annoying. I just stop them from spawning. I understand you got hands full with this and thanks for doing it. Better dungeons was the bomb hope to see it some day again.

**Comment by BlackJar72** [comment]
I might considering re-editing the troll to be slightly quieter -- they should be loud, but probably not compete with the mini-bosses and (possibly) up-coming boss-level tarrasque.
